import smtplib
from email.mime.text import MIMEText


def send_email(subject, body):
    # Configuration
    port = 587
    smtp_server = "live.smtp.mailtrap.io"
    login = "api"  # Your login generated by Mailtrap
    password = "f5e525f6d6071b21c9310d720de800ad"  # Your password generated by Mailtrap

    sender_email = "mailtrap@demomailtrap.com"
    receiver_email = "riteshranjan1620@gmail.com"

    # Create MIMEText object
    message = MIMEText(body, "plain")
    message["Subject"] = subject
    message["From"] = sender_email
    message["To"] = receiver_email

    # Send the email
    with smtplib.SMTP(smtp_server, port) as server:
        server.starttls()  # Secure the connection
        server.login(login, password)
        server.sendmail(sender_email, receiver_email, message.as_string())

    print('Sent')
    